### ISSUE TITLE
Sentence Rephraser?

### ISSUE THREAD

**Issue by grandmasterspoc** [subosito/gingerice#6]
Does this gem provide functionality for the sentence rephraser? (http://www.gingersoftware.com/products/sentence-rephraser#.VucRNZMrKNY)

**Comment by arnoldfungai** [comment]
Try [rginger](https://github.com/yohasebe/rginger)

**Comment by SEOTOolsCentre** [comment]
hi grandmasterspoc ,
do you looking for some[ sentence rephraser](https://seomagnifier.com/online-paraphrasing-tool) to rephrase the sentences?
